name: point_of_sell
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: 
  sqflite_common_ffi: 
  sqflite: 
  get: 
  csv:
  flutter_file_dialog: 
  fluent_ui:
  # qr_bar_code_scanner_dialog:
  simple_barcode_scanner: 
  device_preview:
  flutter_svg:
  pdf: 
  printing:
  # permission_handler: 
  # flutter_lints: 
  # google_fonts:
  shared_preferences: 
  qr_flutter:
  barcode_widget:
  file_picker: 
  # tutorial_coach_mark:    # ! تشرح البرنامج

  path: 
  path_provider: 
  intl: 
  permission_handler: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  assets:
    - assets/icons/
    - assets/image/
  uses-material-design: true
 
flutter_intl:
  enabled: true
